name: Lighthouse Report Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    env:
      VTEX_ID_CLIENT_AUT_COOKIE: ${{ secrets.VTEX_ID_CLIENT_AUT_COOKIE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -f install
      
      - name: Run lighthouse script
        run: |
          npm install -g @lhci/cli
          lhci autorun --config=./lighthouserc-ci.js

      - name: Extract assertions and save to file
        run: |
          jq '.audits | to_entries | map(select(.value.score != null and .value.score < 1)) | .[].key' ./lighthouse-report.json > lighthouse-assertions.txt
      
      - name: Set Date Variable
        run: echo "REPORT_DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Lighthouse Assertions ${{ env.REPORT_DATE }}
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-assertions
          path: lighthouse-assertions.txt